In [3]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 

In [5]:
df = pd.read_csv('E:/AL_ML/CDAC-Training/it_services_tickets_raw.csv')

In [6]:
#Make an array from the hours logged column.
hours_array = np.array(df["hours_logged"])
print(hours_array)

['?' '1.34 ' '7' ... '5' '2' '6.5 hrs']


In [7]:
#Print the shape, the size and the data type of that array.
print("Shape:", hours_array.shape)
print("Size:", hours_array.size)
print("Data type:", hours_array.dtype)

Shape: (49588,)
Size: 49588
Data type: object


In [8]:
#Make an array of the numbers 1 to 50 using arange.
arr_1_to_50 = np.arange(1, 51)
print(arr_1_to_50)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [9]:
#Make 10 evenly spaced numbers between 0 and 100 using linspace.
arr_linspace = np.linspace(0, 100, 10)
print(arr_linspace)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [11]:
#Make an array of 10 zeros and an array of 10 ones.
zeros = np.zeros(10)
ones = np.ones(10)
print("Zeros:", zeros)
print("Ones:", ones)

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
#Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
random_array = np.random.rand(3, 3)
print(random_array)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [16]:
#Make a 2-D array from the hours logged and billing rate columns.
hours_billing_array = np.column_stack(
    (df['hours_logged'], df['Billing Rate (USD)'])
)

print(hours_billing_array)

[['?' '$39.45']
 ['1.34 ' '33.15']
 ['7' '48.10']
 ...
 ['5' '24.94']
 ['2' '$116.76']
 ['6.5 hrs' ' 89.02 ']]


In [17]:
#Print how many dimensions that 2-D array has.
print(hours_billing_array.ndim)

2


In [18]:
#Print the first 5 values of the hours array.
print(hours_array[:5])

['?' '1.34 ' '7' '34.630' '12.76 ']


In [19]:
#Print the last 5 values of the hours array.
print(hours_array[-5:])

['4' '47' '5' '2' '6.5 hrs']


In [20]:
#Print every second value from the first 20 values.
print(hours_array[:20:2])

['?' '7' '12.76 ' '--' '1.660' nan '11.63' '28' '0.59' '253.85']


In [23]:
#Reverse the array.
print(hours_array[::-1])

['6.5 hrs' '2' '5' ... '7' '1.34 ' '?']


In [30]:
#Find the sum of the hours array.
hours_array = np.array(hours_array, dtype=float)
print(np.sum(hours_array))

nan


In [31]:
#Find the mean, the minimum and the maximum of the hours array.
print("Mean:", np.nanmean(hours_array))
print("Minimum:", np.nanmin(hours_array))
print("Maximum:", np.nanmax(hours_array))

Mean: 63.614814913947704
Minimum: -12.5
Maximum: 9888.01


In [32]:
#Find the standard deviation.
print(np.nanstd(hours_array))

497.7190812291573


In [33]:
#Find the median.
print(np.nanmedian(hours_array))

13.13


In [34]:
#Count how many values are missing in the array.
print(np.isnan(hours_array).sum())

12227


In [35]:
#Find the mean while ignoring the missing values.
print(np.nanmean(hours_array))

63.614814913947704


In [36]:
#Replace all the missing values with 0.
hours_no_nan = np.nan_to_num(
    hours_array,
    nan=0
)

print(hours_no_nan)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [37]:
#Count how many values are greater than 100.
print(np.sum(hours_no_nan > 100))

1633


In [ ]:
#Show values greater than 100
print(hours_no_nan[hours_no_nan > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [39]:
#Show the values that are between 10 and 50.
print(
    hours_no_nan[
        (hours_no_nan >= 10) &
        (hours_no_nan <= 50)
    ]
)

[34.63 12.76 15.3  ... 25.23 50.   47.  ]


In [40]:
#Count how many values are negative.
print(np.sum(hours_no_nan < 0))

140


In [41]:
#Replace all the negative values with 0.
hours_positive = hours_no_nan.copy()
hours_positive[hours_positive < 0] = 0

print(hours_positive)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [42]:
#Sort the array from smallest to largest.
sorted_hours = np.sort(hours_positive)
print(sorted_hours)

[   0.      0.      0.   ... 8760.   9888.01 9888.01]


In [50]:
#Find the position of the largest value.
print(np.argmax(hours_no_nan))

10080


In [47]:
#Find the position of the smallest value.
print(np.argmin(hours_no_nan))

606


In [49]:
#Find the 5 largest values.
print(
    np.sort(hours_no_nan)[-5:]
)

[8760.   8760.   8760.   9888.01 9888.01]


In [ ]:
#Round every value to 1 decimal place.
print(
    np.round(hours_no_nan, 1)
)

[0.  1.3 7.  ... 5.  2.  0. ]


In [51]:
#Multiply every value by 2.
print(hours_no_nan * 2)

[ 0.    2.68 14.   ... 10.    4.    0.  ]


In [52]:
#Add 10 to every value.
print(hours_no_nan + 10)

[10.   11.34 17.   ... 15.   12.   10.  ]


In [56]:
#Multiply the hours array by the billing rate array.
billing_rate_array = pd.to_numeric(
    df["Billing Rate (USD)"],
    errors="coerce"
).to_numpy()

revenue = hours_no_nan * billing_rate_array

print(revenue)

[    nan  44.421 336.7   ... 124.7       nan   0.   ]


In [70]:
#Check whether the two arrays have the same length.
print(len(hours_positive) == len(billing_rate_array))

True


In [69]:
#Use np.where to mark values above 24 as slow and the rest as fast.
speed = np.where(
    hours_positive > 24,
    "slow",
    "fast"
)

print(speed)

['fast' 'fast' 'fast' ... 'fast' 'fast' 'fast']


In [68]:
#Make an array of the unique priority values.
priority_array = pd.to_numeric(
    df["PRIORITY"],
    errors="coerce"
).to_numpy()

unique_priorities = np.unique(priority_array)
print(unique_priorities)

[ 1.  2.  3.  4. nan]


In [67]:
#Count how many times each unique priority value appears.
values, counts = np.unique(
    priority_array,
    return_counts=True
)

print(values)
print(counts)


[ 1.  2.  3.  4. nan]
[ 1992  2019  1995  1968 41614]


In [66]:
#Take the first 100 values and reshape them into a 10 by 10 array.
first_100 = hours_positive[:100]

array_10x10 = first_100.reshape(10, 10)

print(array_10x10)

[[0.00000e+00 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
  0.00000e+00 9.00000e+00 1.66000e+00 0.00000e+00]
 [0.00000e+00 1.44000e+00 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01
  5.90000e-01 7.00000e+00 2.53850e+02 4.20000e+00]
 [5.08100e+01 8.01000e+00 6.79400e+01 0.00000e+00 3.27100e+01 0.00000e+00
  6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00]
 [1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01 0.00000e+00 1.30000e+01
  3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00]
 [0.00000e+00 3.92000e+00 2.02200e+01 2.41500e+01 8.40000e+01 0.00000e+00
  2.70000e+01 0.00000e+00 4.00000e+00 2.76000e+00]
 [1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01 5.00000e+00 1.14100e+01
  0.00000e+00 1.80000e+01 1.28000e+02 1.54000e+01]
 [1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02 0.00000e+00
  4.00000e+00 0.00000e+00 2.00000e+00 0.00000e+00]
 [2.05100e+01 1.13300e+01 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00
  0.00000e+00 0.00000e+00 3.40000e+01 1.49200e+01]


In [65]:
#Transpose that 10 by 10 array.
transposed_array = array_10x10.T

print(transposed_array)

[[0.00000e+00 0.00000e+00 5.08100e+01 1.80000e+01 0.00000e+00 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01 0.00000e+00 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01 0.00000e+00 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01 0.00000e+00 3.73680e+02]
 [1.53000e+01 1.01600e+01 0.00000e+00 1.30000e+01 0.00000e+00 1.14100e+01
  0.00000e+00 0.00000e+00 2.00000e+01 1.13800e+01]
 [0.00000e+00 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01 0.00000e+00
  4.00000e+00 0.00000e+00 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01 0.00000e+00 1.80000e+01
  0.00000e+00 0.00000e+00 1.15600e+01 5.80000e-01]


In [64]:
#Flatten it back into a 1-D array.
flattened_array = transposed_array.flatten()

print(flattened_array)

[0.00000e+00 0.00000e+00 5.08100e+01 1.80000e+01 0.00000e+00 1.12600e+01
 1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01 1.34000e+00 1.44000e+00
 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01 4.00000e+00 1.13300e+01
 1.78600e+01 1.09100e+01 7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00
 2.02200e+01 5.26000e+00 3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00
 3.46300e+01 7.23100e+01 0.00000e+00 2.44600e+01 2.41500e+01 1.40000e+01
 9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00 1.27600e+01 2.80000e+01
 3.27100e+01 0.00000e+00 8.40000e+01 5.00000e+00 1.33350e+02 2.29700e+01
 0.00000e+00 3.73680e+02 1.53000e+01 1.01600e+01 0.00000e+00 1.30000e+01
 0.00000e+00 1.14100e+01 0.00000e+00 0.00000e+00 2.00000e+01 1.13800e+01
 0.00000e+00 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01 0.00000e+00
 4.00000e+00 0.00000e+00 6.00000e+00 3.36700e+01 9.00000e+00 7.00000e+00
 3.08400e+01 1.15100e+01 0.00000e+00 1.80000e+01 0.00000e+00 0.00000e+00
 1.15600e+01 5.80000e-01 1.66000e+00 2.53850e+02 3.

In [71]:
#Join two arrays together using np.concatenate.
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

joined_array = np.concatenate(
    (array1, array2)
)

print(joined_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [73]:
#Split an array into 5 equal parts.
split_array = np.array_split(
    hours_no_nan,
    5
)

print(split_array)

[array([ 0.  ,  1.34,  7.  , ..., 22.92, 17.44,  4.47], shape=(9918,)), array([ 0.  ,  0.  , 32.  , ...,  1.  ,  0.  ,  7.66], shape=(9918,)), array([ 6.65,  1.  , 27.47, ..., 58.  ,  1.86,  0.  ], shape=(9918,)), array([11.76,  0.  ,  0.  , ..., 57.1 , 19.04,  0.  ], shape=(9917,)), array([47.52,  5.  ,  5.3 , ...,  5.  ,  2.  ,  0.  ], shape=(9917,))]


In [74]:
#Find the 25th, 50th and 75th percentile.
print(
    np.percentile(
        hours_no_nan,
        [25, 50, 75]
    )
)

[ 0.    6.57 23.6 ]


In [75]:
#Find the cumulative sum of the first 20 values.
print(
    np.cumsum(
        hours_no_nan[:20]
    )
)

[  0.     1.34   8.34  42.97  55.73  71.03  71.03  80.03  81.69  81.69
  81.69  83.13  94.76 167.07 195.07 205.23 205.82 212.82 466.67 470.87]


In [ ]:
#Find the difference between each value and the one before it using np.diff.
print(
    np.diff(hours_no_nan)
)

[  1.34   5.66  27.63 ... -42.    -3.    -2.  ]


In [77]:
#Keep every value inside the range 0 to 100 using np.clip.
clipped_array = np.clip(
    hours_no_nan,
    0,
    100
)

print(clipped_array)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [78]:
#Convert the array to whole numbers.
whole_numbers = hours_no_nan.astype(int)

print(whole_numbers)

[0 1 7 ... 5 2 0]


In [79]:
#Copy the array, change one value in the copy, and show that the original did not change.
original_array = hours_no_nan.copy()

copied_array = hours_no_nan.copy()

copied_array[0] = 999

print("Original:", original_array)
print("Copy:", copied_array)

Original: [0.   1.34 7.   ... 5.   2.   0.  ]
Copy: [999.     1.34   7.   ...   5.     2.     0.  ]


In [80]:
#Save the array to a .npy file and load it back.
np.save(
    "hours_array.npy",
    hours_no_nan
)

loaded_array = np.load(
    "hours_array.npy"
)

print(loaded_array)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [81]:
#Find the total revenue using np.dot on the hours array and the rate array.
total_revenue = np.dot(
    hours_no_nan,
    billing_rate_array
)

print(total_revenue)

nan
